# Site Settings

disqus:              #"your-disqus"

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]

sass:
  sass_dir: assets/css
  style: :nested
